# Generated by Django 4.1.7 on 2023-02-18 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Colori",
            fields=[
                ("idcolore", models.AutoField(primary_key=True, serialize=False)),
                ("descrizionecolori", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Gruppi",
            fields=[
                ("idgruppo", models.AutoField(primary_key=True, serialize=False)),
                (
                    "descrizionegruppo",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tblClienti",
            fields=[
                ("idcliente", models.AutoField(primary_key=True, serialize=False)),
                ("cliente", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "codicecliente",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "rappresentante",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("indirizzo", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="tblOrdini",
            fields=[
                ("idordine", models.AutoField(primary_key=True, serialize=False)),
                ("origineordine", models.IntegerField(blank=True, null=True)),
                ("nordine", models.IntegerField(blank=True, null=True)),
                ("dataordine", models.DateField(blank=True, null=True)),
                ("datacons", models.DateField(blank=True, null=True)),
                ("datacomunicata", models.DateField(blank=True, null=True)),
                ("riford", models.CharField(blank=True, max_length=200, null=True)),
                ("evaso", models.BooleanField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "note_calendario",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "idcliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cal.tblclienti"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="tbldettordini",
            fields=[
                ("iddettordine", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.FloatField(blank=True, null=True)),
                ("prezzo", models.FloatField(blank=True, null=True)),
                (
                    "idcolore",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cal.colori"
                    ),
                ),
                (
                    "idgruppo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cal.gruppi"
                    ),
                ),
                (
                    "idordine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="cal.tblordini"
                    ),
                ),
            ],
        ),
    ]
