# Generated by Django 4.1.7 on 2023-02-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0002_colori_gruppi_tblclienti_tblordini_tbldettordini"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tblordini",
            name="datacons",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
