# Generated by Django 4.1.7 on 2023-02-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cal", "0003_alter_tblordini_datacons"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="origin",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
